name: CI Build

on: 
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
        - "**.go"
        - ".github/workflows/**"


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.23' ]
    steps:
      - name: Set up Go v${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          go version
          go get -v -d ./...

      - name: Cache modules
        uses: actions/cache@v3
        with:
          path: $GOPATH/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go

      - name: Vet code
        run: go vet

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build LDLFAGS="-s" -o nenu_linux_amd64
          GOOS=linux GOARCH=arm64 go build LDLFAGS="-s" -o nenu_linux_arm64
          GOOS=darwin GOARCH=amd64 go build LDLFAGS="-s" -o nenu_darwin_amd64
          GOOS=windows GOARCH=amd64 go build LDLFAGS="-s" -o nenu_windows_amd64.exe

      - name: Prepare release
        run: zip -r nenu-bin.zip nenu_* config.yml.tpl LICENSE themes/
      
      - name: Upload release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: nenu-bin.zip